# Etapa de construção
FROM php:8.1-cli AS build

# Instala dependências necessárias (se houver)
RUN docker-php-ext-install pdo pdo_mysql

# Copia o arquivo index.php para a imagem de construção
COPY index.php /app/

# Etapa de produção
FROM php:8.1-apache

# Copia o arquivo index.php da imagem de construção
COPY --from=build /app/index.php /var/www/html/

# Define permissões para o Apache acessar os arquivos (opcional)
RUN chown -R www-data:www-data /var/www/html

# Define o ServerName para evitar o aviso
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Expor a porta 80 para o servidor Apache
EXPOSE 80

# Iniciar o Apache no primeiro plano (foreground)
CMD ["apache2-foreground"]
