stages:
  - stage: checkStage
    displayName: Check Stage
    jobs:
      - job: checkJob
        continueOnError: false
        displayName: Check Variables
        steps:
          # Get Build Variables
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                if [ "$(Build.Reason)" == "PullRequest" ]; then
                  echo '⚠️ It is a Pull Request ⚠️'
                  echo '⚠️ Only this step and compile will be executed ⚠️'
                  echo ''
                  echo 'Build Reason: $(Build.Reason)'
                  echo 'Pull Request ID: $(System.PullRequest.PullRequestId)'
                  echo 'Target Branch: $(System.PullRequest.TargetBranch)'
                  echo 'Source Branch: $(System.PullRequest.SourceBranch)'
                else
                  echo 'Build Reason: $(Build.Reason)'
                  echo 'Source Branch: $(Build.SourceBranch)'
                  echo 'Source Branch Name: $(Build.SourceBranchName)'
                fi
            displayName: Check Variables

  - stage: buildStage
    displayName: Build Stage
    condition: succeeded('checkStage')
    jobs:
      - job: buildJob
        continueOnError: false
        displayName: Run Build and Cache
        steps:
          # Install Java SDK
          - task: JavaToolInstaller@0
            displayName: 'Install Java SDK'
            inputs:
              versionSpec: $(java-version-spec)
              jdkArchitectureOption: $(java-jdk-architecture-option)
              jdkSourceOption: $(java-jdk-source-option)
              cleanDestinationDirectory: $(java-jdk-clean-directory)

          # Create Cache Maven Directory
          - script: |
              mkdir -p /home/vsts/work/1/.m2/repository
            displayName: Create Cache Directory

          # Cache Maven Dependencies
          - task: Cache@2
            displayName: Cache Maven
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
              path: $(cache-maven-path)

          # Package the Project
          - task: Maven@4
            displayName: Maven Compile
            inputs:
              goals: $(build-maven-goals)
              mavenPomFile: $(build-maven-pom-file)
              options: $(build-maven-options)
              mavenOptions: $(build-maven-extra-options)
              javaHomeOption: $(build-java-home-option)
              jdkVersionOption: $(build-java-jdk-version-option)
              jdkArchitectureOption: $(build-java-jdk-architecture-option)
              publishJUnitResults: false

          # Archive Build Artifact
          - task: ArchiveFiles@2
            displayName: Archive Build Artifacts
            inputs:
              rootFolderOrFile: $(archive-artifact-root-folder)
              includeRootFolder: false
              archiveType: $(archive-artifact-type)
              archiveFile: $(archive-artifact-file)
              replaceExistingArchive: true

          # Publish Build Artifact
          - task: PublishBuildArtifacts@1
            displayName: Publish Build Artifact
            inputs:
              pathToPublish: $(publish-artifact-path)
              artifactName: $(publish-artifact-name)

  - stage: deployStage
    displayName: Deploy Stage
    condition: succeeded('buildStage')
    jobs:
      - job: Deploy
        continueOnError: false
        displayName: Deploy
        steps:
          # Download Build Artifacts
          - task: DownloadBuildArtifacts@0
            displayName: Download Build Artifact
            inputs:
              artifactName: $(download-artifact-name)
              downloadPath: $(download-artifact-path)

          # Deploy to Azure Web App
          - task: AzureRmWebAppDeployment@4
            displayName: Deploy to Azure
            inputs:
              ConnectionType: $(web-app-connection-type)
              azureSubscription: $(azure-subscription)
              appType: $(web-app-type)
              WebAppName: $(azure-web-app-name)
              packageForLinux: $(package-artifact)
              RuntimeStack: $(web-app-runtime-stack)

          # Verify Web App Update Status
          - task: AzureCLI@2
            displayName: Verify Update Status
            inputs:
              azureSubscription: $(azure-subscription)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                STATUS=$(az webapp show --name $(azure-web-app-name) --resource-group $(azure-resource-group) --query "state" -o tsv)
                if [[ "$STATUS" != "Running" ]]; then
                  echo "⚠️ Update failed. Web App is not running." && exit 1
                else
                  echo "✅ Web App updated and running successfully."
                fi