stages:
  - stage: checkStage
    displayName: Check Stage
    jobs:
      - job: checkJob
        continueOnError: false
        displayName: Check Variables
        steps:
          # Get Build Variables
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                if [ "$(Build.Reason)" == "PullRequest" ]; then
                  echo 'It is a Pull Request ⚠️'
                  echo ''
                  echo 'Build Reason: $(Build.Reason)'
                  echo 'Pull Request ID: $(System.PullRequest.PullRequestId)'
                  echo 'Target Branch: $(System.PullRequest.TargetBranch)'
                  echo 'Source Branch: $(System.PullRequest.SourceBranch)'
                else
                  echo 'Build Reason: $(Build.Reason)'
                  echo 'Source Branch: $(Build.SourceBranch)'
                  echo 'Source Branch Name: $(Build.SourceBranchName)'
                fi
            displayName: Check Variables

  - stage: buildStage
    displayName: Build and Push
    condition: succeeded('checkStage')
    jobs:
      - job: buildJob
        continueOnError: false
        displayName: Build
        steps:
          # Build Docker Image
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              command: build
              repository: $(docker-image-name-repository)
              dockerfile: $(docker-dockerfile-path)
              containerRegistry: $(docker-registry-service-connection)
              tags: $(docker-tag)
              buildContext: $(docker-build-context)
              # arguments: $(docker-build-arguments)

          # Push Docker Image
          - task: Docker@2
            displayName: Push Docker Image
            inputs:
              command: push
              repository: $(docker-image-name-repository)
              containerRegistry: $(docker-registry-service-connection)
              tags: $(docker-tag)

  - stage: deploySate
    condition: succeeded('buildStage')
    displayName: Deploy
    jobs:
      - job: deployJob
        continueOnError: false
        displayName: Deploy
        steps:
          # Deploy to Azure Container Apps
          - task: AzureContainerApps@1
            displayName: Deploy to Azure
            inputs:
              azureSubscription: $(azure-subscription)
              containerAppName: $(azure-container-app-name)
              resourceGroup: $(azure-resource-group)
              imageToDeploy: "$(azure-container-registry)/$(docker-image-name-repository):$(docker-tag)"

          # Update Container App
          - task: AzureCLI@2
            displayName: Update Container App
            name: UpdateContainer
            inputs:
              azureSubscription: $(azure-subscription)
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              inlineScript: |
                az containerapp update -n $(azure-container-app-name) -g $(azure-resource-group) --container-name $(azure-container-app-name) -i $(azure-container-registry)/$(docker-image-name-repository):$(docker-tag)

          # Verify Update Status
          - task: AzureCLI@2
            displayName: Verify Update Status
            inputs:
              azureSubscription: $(azure-subscription)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                STATUS=$(az containerapp show -n $(azure-container-app-name) -g $(azure-resource-group) --query "properties.provisioningState" -o tsv)
                if [[ "$STATUS" != "Succeeded" ]]; then
                  echo "⚠️ Update failed. Check logs for details." && exit 1
                else
                  echo "✅ Update completed successfully."
                fi